language: php

php:
  - 5.6
  - 7.0

env:
  global:
    - SIMPLETEST_DB=sqlite://yoda/devtest
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"

before_install:
  - composer self-update

install:
  - cd .. && composer create-project drupal-composer/drupal-project:8.x-dev drupal --stability dev --no-interaction


script:
  - cd $TRAVIS_BUILD_DIR/../drupal/web
  - mkdir ./modules/pole_manager/ && cp -R $TRAVIS_BUILD_DIR/* ./modules/pole_manager/
  - ../vendor/bin/drush site-install --verbose --yes --db-url=sqlite://yoda/devtest
  - ../vendor/bin/drush runserver $SIMPLETEST_BASE_URL &
  - until curl -s $SIMPLETEST_BASE_URL; do true; done > /dev/null
  - ../vendor/bin/phpunit -c core --group pole_manager
