language: php

php:
  - 5.6
  - 7.0

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - composer self-update

install:
  - cd .. && composer create-project drupal-composer/drupal-project:8.x-dev drupal --stability dev --no-interaction
  - mkdir drupal/modules/pole_manager && cp -R Pole-Manager/* drupal/modules/pole_manager/
  - cd drupal/core && cp phpunit.xml.dist phpunit.xml
  - sed 's/"SIMPLETEST_BASE_URL" value=""/"SIMPLETEST_BASE_URL" value="dev.local"/' phpunit.xml
  - sed 's/"SIMPLETEST_DB" value=""/"SIMPLETEST_DB" value="mysql://yoda:obiwan@localhost/devtest"/' phpunit.xml

script: ../vendor/bin/phpunit --group pole_manager
