language: php

php:
  - 5.6
  - 7.0
  
mysql:
  database: drupal 
  username: root 
  encoding: utf8
  
before_install: 
  - composer self-update
  
install: 
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer create-project drupal/drupal drupal
  - composer global require drush/drush:8.*
  - phpenv rehash
  - mv drupal ../drupal
  - ls ..
  - mysql -e 'create database drupal;'
  - yes | drush si --db-url=mysql://root@localhost/drupal site-install standard install_configure_form.enable_update_status_module=NULL install_configure_form.enable_update_status_emails=NULL
  - echo "mv module to appropriate folder"
  - echo "drush pm pole_manager"
