language: php

php:
  - 5.6
  - 7.0

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - composer self-update

install:
  - cd .. && composer create-project drupal-composer/drupal-project:8.x-dev drupal --stability dev --no-interaction
  - cp -R Pole-Manager/* drupal/modules/pole_manager/
  - #TODO: create phpunit.xml from phpunit.xml.dist

script: cd drupal/core && ../vendor/bin/phpunit ../modules/pole_manager/
