language: php

php:
  - 5.6
  - 7.0
  
mysql:
  database: drupal 
  username: root 
  encoding: utf8
  
before_install: 
  - composer self-update
  
install: 
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer create-project drupal/drupal drupal
  - composer global require drush/drush:8.*
  - phpenv rehash
  - mysql -e 'create database drupal;'
  - drush si --db-url=mysql://root@localhost/drupal
  - cd core
