action.configuration.checkout_pole:
  type: action_configuration_default
  label: 'Checkout selected poles to a club member configuration'

action.configuration.checkin_pole:
  type: action_configuration_default
  label: 'Checkin selected poles configuration'
